export { Header } from "./header/Header";
export { Footer } from "./footer/Footer";
export { Main } from "./main/Main";
export { CardFilm } from "./card/CardFilm";
export { CardQA } from "./cardQA/CardQA";
export { CountTicket } from "./countTicket/CountTicket";
export { MoviesList } from "./moviesList/MoviesList";
export { MoviesListMain } from "./moviesList/MoviesListFilter";
export { MoviesContainer } from "./moviesList/MoviesContainer";
export { MainCartList, FooterTotal } from "./moviesList/MainCartList";
export { Filter } from "./filter/Filter";
export { Review } from "./rewievs/Review";
export { Reviews } from "./rewievs/Reviews";
export { PosterMovie } from "./poster/PosterMovie";
export { PostContainer } from "./poster/PostContainer";
export { ReviewContainer } from "./rewievs/ReviewContainer";
